name: Create Episode Cover Images

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  run-script:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use the PAT for authentication

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install pandas pillow  # Install the required Python packages

      - name: Run the script
        run: python episode-update-upload.py  # Run the script
        working-directory: src

      - name: Commit and Push changes
        run: |
          git config --global user.name 'Austin Songer'
          git config --global user.email 'a.songer@protonmail.com'
          git add . 
          git commit -m "Add New Podcast Covers"  # Create a commit
          git remote set-url origin https://austinsonger:${{ secrets.GH_PAT }}@github.com/austinsonger/Podcast-Automation-with-Transistor.fm.git
          git push  # Push the commit to the repository
