name: Audio Transcription

on:
  workflow_dispatch:

jobs:
  transcribe-audio:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        pip install pandas
        pip install SpeechRecognition
        pip install pydub

    - name: Run transcription script
      run: python episode-transcription.py
      working-directory: src

    - name: Commit and Push changes
      run: |
        git config --global user.name 'Austin Songer'
        git config --global user.email 'a.songer@protonmail.com'
        git add . 
        git commit -m "Add new transcription "  # Create a commit
        git remote set-url origin https://austinsonger:${{ secrets.GH_PAT }}@github.com/austinsonger/Podcast-Automation-with-Transistor.fm.git
        git push  # Push the commit to the repository
